added testing and pyrdfstore
vliz-be-opsci/py-sema pull request #49
Opened 2024-06-19 11:14 UTC by cedricdcc

This PR adds the following:

- Adds Makefile with single testing and graphdb testing capabilities
- yml .github workflow fro PR testing
- submodule folder layout
- the original code and testing from py-rdf-store with some small refactoring on where the variables come from

Issues tackled in this PR:

- #37 
- #43 
- #38 
- #40 
- #41
- #48

2024-06-26 11:03 UTC, marc-portier requested changes
think we should do the clean split up prior to merge
as I think other parts of the sema-group are going to use and reference it, and would then lead to possible conflicts 

all other remarks can probably be moved into issues that various people can take up

2024-06-26 11:03 UTC, marc-portier commented on tests/util4tests.py
this file is a remnant of our cookiecutter (which could use an update)
considering we have started using `conftest.py` nowadays we might as well include the content of this file inside that one?

2024-06-26 12:07 UTC, marc-portier commented
also slightly worrying that the automated tests seem to be failing
best to make sure that gets resolved too (strangely my own experience is that tests seem to run nicely locally)

also: the requested split / reposition of the **clean stuff should be accompanied by a reposition of the matching tests I guess

2024-06-26 15:12 UTC, marc-portier commented on tests/conftest.py
> +# TODO: enable this back when pyrdfstore is implemented in sema
mysterious message
what "this" should be enable?

2024-06-26 15:58 UTC, marc-portier commented
@cedricdcc 
found some time today to give a hint about that reorganiszation of the cleaning code 
see https://github.com/vliz-be-opsci/py-sema/tree/fix/commons-clean

possibly useful to merge into this branch / PR

2024-07-02 06:45 UTC, cedricdcc commented on sema/commons/j2/j2_functions.py
> +            "xsd": xsd_format,
mentioned in #51

2024-07-02 06:51 UTC, cedricdcc commented on sema/commons/j2/j2_functions.py
mentioned in #52

2024-07-02 09:39 UTC, cedricdcc commented on sema/__init__.py
> +__all__ = ["commons"]
mentioned in #53

2024-07-02 11:25 UTC, marc-portier commented
automated tests still failing -- any clue about the why?

2024-07-03 06:38 UTC, cedricdcc commented
> automated tests still failing -- any clue about the why?

It has something todo with the coverage tests from @JotaFan.

Installing collected packages: coverage, coverage-badge
Successfully installed coverage-7.5.4 coverage-badge-1.1.1
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.4/x64/bin/coverage-badge", line 5, in <module>
    from coverage_badge.__main__ import main
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/coverage_badge/__main__.py", line 7, in <module>
    import pkg_resources

2024-07-03 14:24 UTC, merged